### ISSUE TITLE
Slider min-max validations missing

### ISSUE THREAD

**Issue by rsram312** [miracleonyenma/custom-vue-range-slider#1]
Hi - I came across your component shared on a blog and I was planning to use something similar. 
Currently, I do not see validations ensuring slider max is always greater than slider min - or in other words preventing to slider min to be more than slider max. 
Were you planning to add it to your component by any chance ? @miracleonyenma

**Comment by miracleonyenma** [comment]
Hey @rsram312, thanks for taking notice of that.
I don't have any particular reason why I didn't add the validations plus I was trying to keep the tutorial as simple as possible.

Would you be open to add that validation functionality?

**Comment by rsram312** [comment]
@miracleonyenma I actually gave it a try. With the current code, I was having a hard time to get the validations to ensure min to be always less than max could be added to work.

So, any suggestions / changes from you on that would be helpful.

**Comment by AntiCZ** [comment]
@miracleonyenma Hi, pull request on it: https://github.com/miracleonyenma/custom-vue-range-slider/pull/5
I am not a fun of two ways bindings so you may find better way.

**Comment by miracleonyenma** [comment]
Merged! @AntiCZ thank you so much.

@rsram312, you can check it out #5
