### ISSUE TITLE
firefox css bug

### ISSUE THREAD

**Issue by Frallen** [miracleonyenma/custom-vue-range-slider#2]
Hi, please check your css code in the firefox browser, it is not displayed correctly and dragging sliders does not work

[Link](https://custom-vue-range-slider.netlify.app/)

![image](https://github.com/miracleonyenma/custom-vue-range-slider/assets/31008998/46e70bb7-4d09-4972-bcb6-7b445137cd16)

@miracleonyenma

**Comment by AntiCZ** [comment]
@Frallen, @miracleonyenma  Fixed by https://github.com/miracleonyenma/custom-vue-range-slider/pull/6
